apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-api
spec:
  template:
    spec:
      containers:
        - name: betting-api
          image: ghcr.io/thranox/betting-api:98f2cd9598cbf325d96953b3326b55f2cf5695d9
