apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-api
spec:
  template:
    spec:
      containers:
        - name: betting-api
          image: ghcr.io/thranox/betting-api:8d40a756e48561a3551e0d7638a279bf0eb9d65f
