---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: betting-prod
spec:
  encryptedData:
    .dockerconfigjson: AgCE5jx4dtXmM9H3kQTohzl9Ejdi229AG1P/dsNSnFKmFVkwcWtkWQ+15RrId4+RAnUdG+hpOVo1VCofmSLwFaP1r/u4oCAwpzuFbggTbLwhTeaPzaM2NMqaPVQPEVzMmflps6bhqQSlHvF2appAtmMSe4EW2wIfdIrk61nz+HRU3R01FOl9VuXZnPIXJen14KD1DC183EUVei5NGFTdNhKY1OKAzzUvsiyOeI6PhnJ5HL84qWP+W/hOkhV61+5EuxWPoaoiUwOepiAen+fEAjEmVkUERq5soGNRr2jMsP4o4HzGSineP4pahTKqQRxca1XfYdYaB7FsMG5/rNhmE5hAjeAMMBHIFFuZFX2ZgOR9JvEC1S7R5vWLMf7KRoAAhzNJ5pl3XYElKPtNBMau4NR9mperEnb4tqTqLMDOxTl7KVexToO318qyXNFpKhLmVHeGJ7KOhn8zBdeG5GC0+2E73yli1ZLPoASlPiEFEj2dJyz1PE99vst4GjuLpYnVhAl/mQ6hy2lr99zKralahomR/YvgPdNVUWdaO+QN+WYXYLx9A2Cw3ksT0ev1MSXrR1l2KqCrxMaf6FewBGymQQE79ygGeIudtgJWOSzKngl5QDpr3yTe6QJEaEAlEaNb4DGlPCrdw7kw95oclDgcd89YSXqytzQS2BLiTJ7Nxu9KqvNV6gf4iCJr661nJn5F0paaFu9KxMTRY6qkrv5Uaa+VieUMRjdzmp3/hethoXegBRKVKj9kUWXLSymYQ16fZZ1TjJLP9qLAW/14+DcqX3KtNP5aoQkY2H/4kDAxqnU1ekGKmJ+++lF8jNm2oLHvVoB2CSoeKkWsqQZ9P8FkaConAFy6DS+ZRLcfeEFf7MVeGSiivuOQsKYGzMH5KkSXcPdtJ8d6GYQO/K392crPI/J0wKF1aFICtCvROq/v
  template:
    metadata:
      name: ghcr-secret
      namespace: betting-prod
    type: kubernetes.io/dockerconfigjson
