apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: betting-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - thranox.com
      secretName: api-tls
  rules:
    - host: thranox.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: betting-api
                port:
                  number: 80
