apiVersion: apps/v1
kind: Deployment
metadata:
  name: betting-api
spec:
  template:
    spec:
      containers:
        - name: betting-api
          image: ghcr.io/thranox/betting-api:13d21d5fba9f30d06266f2b1776e065a7b4f16c9
