namespace: betting-dev
resources:
  - ../../base
  - sealed-ghcr-secret.yaml
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: betting-api
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.thranox.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.thranox.com
      - op: replace
        path: /spec/tls/0/secretName
        value: api-tls-dev
    target:
      kind: Ingress
      name: betting-api


