---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: betting-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCRrtajKsXv0OHvXkmWieShuFioB1WeQyfu5h0uDZ9mjJ2RIEj2eBYZJnp2+3xHFgKGMawHNfqZC/2duplLfv1zKgU60ys47p9xIgBD/gCom3OV2WZjduC+PH6tS/8bULniI4H9Fi6oQYNnhgdC0U8Oq7pGruYA2dWE0Aci5vMxYzYedUsqd/ZZ9MFXi7RKSbBfcgGllMS0oN7axJlt2oR5DCIMXGzj0Ns2KuPumoDYHknmTkdHd4TLNgtdvI0Xygj2ltBPSeImX5BzLfwmM0kp/0wmy+5GLZJ1b2R6H/9hqsBS7lt/8SWvBYYNvZcJT+wBAgO0aFdPND8+TNN6g2n+a8Zg36FXlx7m3wgMPJeaZ7TE7ldrBbtBZUxJHMKPs2auGvgz+4KNdn07W3D50If9KJvBGJwzyBD04QkZrxVjc8fI7w7Zyr3FUQWUGH1bAvOVoIal846Ij06HqCy8RQQmNf5tFqr6tALwr0i0fQXTKDVFo/UziSlOzs1mbeqMIy74pcQHg9UZNBfyt7hNPnaGqUSzNG8b/88b3gjBPkB9jJU+P4G69CVmxT30iRwYACwRvEN9W83L//CJ+vIQ4d510SzosybHNxGiHk8oYNvc3t9GU2pJOEf8ILSMq0VfH65hwyvMupBAMxErb5eKcTGv5jmdU8ieFm5OK7Lb0lxnSMn5nRwBtktO9hEhkEILYy+idcZMPmfJWUJ3Ep+sHsoW5z8hx8ew03G4Wy0qIE6X84G5Qww4iEY6wWBquBHD2Qvu0p65/WD/La422z2f6OWwKhREi9QmYu3kUMASDc7NB/BM+xeZp6gk1hfrctb2jmmNsS0dQk/3OVfPJj9mCEdZeHc4iyMSlQ2O7hOe2RZgq1MjBWw6Se9Xi9lbifv95+t9l5tWPsKBLX+fUPONylvWHiVjf1yaeTx7ykfQ
  template:
    metadata:
      name: ghcr-secret
      namespace: betting-dev
    type: kubernetes.io/dockerconfigjson
