---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: betting-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCzEFJsAZnp/XEOD4J3eYeBNeUtu4hVNUJ3uAnu6CFw3yQWVbUF+T8233pkezKWItT7fNVtF/GQ4JdZyzvfSYUrBOpg1lKkToeer4p7Rd7GJTI38HkuPPGxC7FrnF7Gl7NF4XlVcKtbATLZZEal26YKi14kJyfZzSt3lx1h+HrNG/JFZAePR9IqfLJsVQqKXw+K0gNCD7a7KDuzrOWl/NJMNroDdM9eKUQBLLXVHjT5n3onrokWvwQW9jM8MRXfB7TnnsJG6RLmYijwXIVO4TIE3yQDAO1WRLUbKqsXbZ5wvJ5Fck7HXsVKZqbNi1D1CLCFrEN1TgFT7y3nDwKgu9EFgAJfM/kFrMoHKuVpAUEDPMIDB6gbBVN6gvMnR9tn4/DdBw0wTs6NqYPCgprqWNqkZzSxEMnaaK7OG2CgYSpLvYd4US7T1+l/oWOZmKoK6k18hKXaHd8oxQeRarfm22s0+yM8xRlRMJEOQd7PjgBvaKtUZmh0LeZy83KqyFTrzzWPxgx93i5317q3gI/Z6Hbm4cazn4MFHjbQLB9/WNdzqABjsRUsjY2EkwvOX3gXuK7sDAKfdHNVJlcQfqe9TPgrrr1BypK0Z1RIILAz89bmFrlrrMwThRBc36ENYiNDyNO/c4Sa9RSOXCIIWfh0LCe+TxFRUzUgXc2ZyNDCmGVNYtexrVcCB4blvVcJRhwuFhXeCDIWvsN9El3iAAmO5x38opK8t31oUJjr4I/4blGW7+T62ZQLHo9j5ADftK1G/qZu/QmvoLy3rsx+VI9lQDPVOntetDarVPJF8XNUnh+2rUhDR1hz8MxJROQG7iSMc/aCdn7Vs19RFlLLxDdOrixVSabhg7SOfI7cHeFvTP4bvHM7HF3w++rH8Imad6/1oQoeDqtfuu60sUTp/icoWQiBHO+C/POT/WGMlblTFVWi5JBJ65uZuwgOFA5d1X8t5OIsUlUSjySEv0nUot6V00E6ki/OKiY6hAhtWkMLfMQXor5SsjzDj9u5m/lm8pA6LBnMjXFll0GoDRoIxZY4YzgAIFjYFvq6GEglaoucbc6L9jWmvYYt20f7gMursEsEvCHN1AKG1iS9XQw=
  template:
    metadata:
      name: ghcr-secret
      namespace: betting-dev
    type: kubernetes.io/dockerconfigjson
